---

- name: make ~/venvs folder
  file:
    name: ~/venvs/
    state: directory

- name: download get-pip.py
  become: true
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp

- name: install pip
  become: true
  shell: "python /tmp/get-pip.py"

- name: delete get-pip.py
  become: true
  file:
    state: absent
    path: /tmp/get-pip.py

- name: install virtualenv
  become: true
  become_user: root
  shell: pip install --upgrade virtualenv
