---

- name: make ~/venvs folder
  shell: mkdir -p ~/venvs

- name: install pip
  become: true
  become_user: root
  shell: curl https://bootstrap.pypa.io/get-pip.py | python

- name: install virtualenv
  become: true
  become_user: root
  shell: pip install --upgrade virtualenv
