---

- name: make ~/venvs folder
  shell: mkdir -p ~/venvs

- name: install pip
  become: true
  become_user: root
  shell: curl https://bootstrap.pypa.io/get-pip.py | python

- name: install virtualenv
  become: true
  become_user: root
  shell: pip install --upgrade virtualenv

- name: Initiate neovim2 virtualenv
  pip: virtualenv=~/venvs/neovim2
       virtualenv_python=" ~/.pyenv/versions/2.7.13/bin/python"
       name=neovim

- name: Initiate neovim3 virtualenv
  pip: virtualenv=~/venvs/neovim3
       virtualenv_python=" ~/.pyenv/versions/3.6.1/bin/python"
       name=neovim
