---
- name: installing neovim dependencies
  become: true
  package: pkg={{item}} state=present
  with_items:
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
- name: clone neovim repo
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: ~/src/neovim
    version: v0.2.0

- name: install neovim
  become: true
  shell: make && make install
  args:
    chdir: "{{ ansible_env.HOME }}/src/neovim"
